// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlKePCck6LxJPMvZwCdJhP5rDeHSNxqy4',
    appId: '1:736381078339:web:853725370a08318cd7bdf6',
    messagingSenderId: '736381078339',
    projectId: 'flutter-tests-bbe7e',
    authDomain: 'flutter-tests-bbe7e.firebaseapp.com',
    storageBucket: 'flutter-tests-bbe7e.appspot.com',
    measurementId: 'G-V4B7SNSMZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVD0IvoEhkr7iPFiIf4nxmf-e5mRDfqW0',
    appId: '1:736381078339:android:f70778cd4a584db4d7bdf6',
    messagingSenderId: '736381078339',
    projectId: 'flutter-tests-bbe7e',
    storageBucket: 'flutter-tests-bbe7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa9_T9Q2aWgCtH0DwNere9XCklk2OEBWY',
    appId: '1:736381078339:ios:c0051cb61c190a9dd7bdf6',
    messagingSenderId: '736381078339',
    projectId: 'flutter-tests-bbe7e',
    storageBucket: 'flutter-tests-bbe7e.appspot.com',
    iosBundleId: 'com.edugaon.flutterTestOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa9_T9Q2aWgCtH0DwNere9XCklk2OEBWY',
    appId: '1:736381078339:ios:a34316a1d7410acdd7bdf6',
    messagingSenderId: '736381078339',
    projectId: 'flutter-tests-bbe7e',
    storageBucket: 'flutter-tests-bbe7e.appspot.com',
    iosBundleId: 'com.edugaon.flutterTestOne.RunnerTests',
  );
}
